### ISSUE TITLE
Will you be updating this?

### ISSUE THREAD

**Issue by PrayerfulDrop** [cjramseyer/Garbage-Collection#1]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Write your question here

Hoping to discover if you will be fixing the issues of displaying in Home Assistant until HA adds calendar modification capabilities in the CORE.  Heavily use Bruxy70's implementation but it is currently limping along.

**Comment by cjramseyer** [comment]
Good day.  Yes, I plan to do my best to maintain this.  Vaclev did an awesome job developing this HACS integration.  I was disappointed to see it go.  My intent is to maintain his original vision, and try to makes fixes if I can.

I tried the HA local calendar, and that feature is not ready for prime time in my opinion.  There are even issues deleting it once it has been created that still need to be solve.
